### ISSUE TITLE
PerformSSZCheck doesn't use value from value.yaml

### ISSUE THREAD

**Issue by imnisen** [prysmaticlabs/go-ssz#120]
Hi, as in the test function of `PerformSSZCheck`:

https://github.com/prysmaticlabs/go-ssz/blob/6d5c9aa213ae42b6b1b2f45d623b535e96922416/spectests/generic_test.go#L677

When performing the valid check, the current logic is check:

```
deserialize(serialized_bytes) returns error?
serialize(deserialize(serialized_bytes))  =?  serialized_bytes
```

However, as the [spec-test](https://github.com/ethereum/eth2.0-specs/tree/dev/tests/formats/ssz_generic#conditions) says, we should check :

```
deserialize(serialized_bytes) =? yaml_value
serialize(yaml_value) =? serialized_bytes
```

So why not use the passed the `yamlPath` to get the value?

On the other hand, the value written in the yaml file is also encoded(some way serialized) in the ssz format. So we need to decode(deserialize) it to get the origin value. Oh, that seems strange and not independent. Is this the reason why you not use it?

Refer to the test case generator code below:

[How the test case generated](https://github.com/ethereum/eth2.0-specs/blob/7b43a3d7724f9b51c373eefe7c047a01c8e55634/tests/generators/ssz_generic/ssz_test_case.py#L7)

[How to encode value to yaml file](https://github.com/ethereum/eth2.0-specs/blob/7b43a3d7724f9b51c373eefe7c047a01c8e55634/tests/core/pyspec/eth2spec/debug/encode.py#L8)

**Comment by rauljordan** [comment]
Hi @imnisen we are deprecating and discontinuing this project due to serious problems. The right way to use ssz is with https://github.com/ferranbt/fastssz
